### ISSUE TITLE
When using Device message type with multiple recipients no recipient is selected

### ISSUE THREAD

**Issue by fatganz** [Paragraph1/php-fcm#1]
Was randomly getting 400 response from FCM API while sending push notifications. phpFCM Client silently skips adding any recipient when there's more than one available in Message.
Expected behavior should be selecting the first recipient by default or throw an exception which will explain that there's no possibility to send to multiple recipients with Device type.

**Comment by palbertini** [comment]
Confirmed. 
Message will now throw an InvalidArgumentException, when trying to add a 2nd device-type recipient. Solves the problem you had?

**Comment by fatganz** [comment]
This should allow others efficiently catch the problem early! Thanks for your library guys.
