### ISSUE TITLE
Ability to set content_available flag

### ISSUE THREAD

**Issue by BusfyJan** [Paragraph1/php-fcm#28]
I need to set **content_available** flag to my push notification.
Is it possible to implement that flag?

Doc reference: https://firebase.google.com/docs/cloud-messaging/concept-options 
(search for _content_available_)

**Comment by oori** [comment]
```$message->setContentAvailable()```  ?
https://github.com/Paragraph1/php-fcm/blob/master/src/Message.php#L131

**Comment by BusfyJan** [comment]
I must have missed this one, thank you :)
