### ISSUE TITLE
Support for multicast messages

### ISSUE THREAD

**Issue by fela98** [Paragraph1/php-fcm#6]
According to the [FCM HTTP API reference](https://firebase.google.com/docs/cloud-messaging/http-server-ref), it is possible to send multicast messages. You can send up to 1000 push notifications in one request by specifying the registration ids inside an array with the key "registration_ids".

When I try to add more than one device to a message I get the following error:
`when sending to single devices only one recipient is allowed`

Could we make it possible to add multiple recipents to a message and if there are more than recipient, the registration tokens are put inside a "registration_ids" array?

Would really like it as we are sending multiple thousand messages to individual recipients. We can´t use topics because we have some internal code that decides what message gets sent to whom which was too complex to do with topics and conditions in FCM.

**Comment by fela98** [comment]
Added a Pull Request #7

**Comment by palbertini** [comment]
Thanks for your pull request. Merged, tagged and composer ready.
