### ISSUE TITLE
Call to undefined method paragraph1\phpFCM\Client::injectGuzzleHttpClient()

### ISSUE THREAD

**Issue by wikichua** [Paragraph1/php-fcm#8]
Any help with this?

Call to undefined method paragraph1\phpFCM\Client::injectGuzzleHttpClient()
about few months ago, this method was working. but now not anymore

i did not see this method in Client file
all i saw is injectHttpClient() 
but this aint working.

**Comment by kbielenberg** [comment]
Yes, injectGuzzleHttpClient() changed to injectHttpClient(), because you can inject any client that implements GuzzleHttp\ClientInterface. So you have to use injectHttpClient instead of injectGuzzleHttpClient now. What is the error you are getting?
