### ISSUE TITLE
setIcon & setSound

### ISSUE THREAD

**Issue by lttin0912** [Paragraph1/php-fcm#9]
I use this package in laravel 5.3 but I can not set icon and sound when mobile receive push notification

$notification = new Notification($request->title, $request->message);
$notification->setSound(public_path()."/sounds/push.mp3");
$notification->setBadge(1);
$notification->setIcon(public_path()."/images/logo.png");
$message->setNotification($notification)

**Comment by kbielenberg** [comment]
What's the error you are getting? Do you use the newest version?

**Comment by lttin0912** [comment]
Sorry. I found my mistake. Thank you.
